### PR TITLE
If use `generate-i18n` in `lint-staged` with `--fail-if-unused` flag then `lint-staged` skips error inside script

### LINKED ISSUE #84: If use `generate-i18n` in `lint-staged` with `--fail-if-unused` flag then `lint-staged` skips error inside script
Perhaps this behavior is related to the operation of the fs

### PR DESCRIPTION
**Pull request by LamaEats**
Resolve #84 

image

### CODE REVIEW

File: bin/generate-i18n.js [hunk 1]
```diff
@@ -1,3 +1,10 @@
 #!/usr/bin/env node
 
-require('../lib/cli/generate-i18n');
+"use strict";
+
+(async function main() {
+    await require("../lib/cli/generate-i18n")
+        .main()
+        .then(() => process.exit(0))
+        .catch(() => process.exit(1));
```
Comment (awinogradov) [inline bin/generate-i18n.js:9]: 👍🏼

**Review by awinogradov — APPROVED** [review]
